FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential meson pkg-config libzstd-dev libcurl4-openssl-dev libssl-dev

ADD . /repo
WORKDIR /repo
RUN meson build
WORKDIR /repo/build
RUN ninja
